baseURL = 'https://ascentdatasolutions.com/'
languageCode = 'en-us'
title = 'Ascent Data Solutions'
themes="hugo-theme-air"
sectionPagesMenu = "mainmenu"

paginate = 1
DisqusShortname = ""
Copyright = "All rights reserved - 2022"
canonifyurls = true

[author]
  name = ""

[permalinks]
    post = "/post/:year/:month/:day/:slug"

[params]
  description = "From Data Science to customized BI solutions"
  cover = "images/screen4.jpg"
  author = "syui"
  authorlocation = ""
  authorwebsite = "https://syui.cf/hugo-theme-air"
  bio= "my bio"
  logo = "images/user.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "syui"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  mainSections = ["post"]

[menu]

  [[menu.navbar]]
    identifier = "contact"
    name = "Contact"
    pre = "<i class='fas fa-envelope'></i>"
    url = "/contact"
    weight = 300

  [[menu.navbar]]
    identifier = "blog"
    name = "Blog"
    pre = "<i class='fas fa-envelope'></i>"
    url = "/"
    weight = 200

  [[menu.navbar]]
    identifier = "about"
    name = "About"
    pre = "<i class='fas fa-user'></i>"
    url = "/about"
    weight = 100


